#' extr_timestamps function
#'
#' @description Internal function to extract timestamps from Excel files generated by a
#'   Li-Cor 6800 system
#'
#' @param list_files Inherited argument from Rapid_aci_correction function
#' @param timestamp_column Inherited argument from Rapid_aci_correction function
#'
#' @return Timestamp as read in Excel files produced by the LI-Cor portable photosynthesis
#'   systems LI6800 (only).


extr_timestamps <- function(list_files,
                            timestamp_column) {

  timestamps <- vector("character", length(list_files))
  range <- paste0(timestamp_column, 17)
  
  for(i in 1:length(list_files)) {
    suppressMessages(x <- readxl::read_excel(list_files[i], range = range, col_names = FALSE))
    if(length(x) == 0) {
      timestamps[i] <- NA
    } else {
      timestamps[i] <- round(x, digits = 0)
    }
  }
  
  output <- unlist(timestamps)
  return(output)
}
